<template>
  <section class="suite-page">
    <div class="suite-titlebar"><div><h1>我的素材</h1><p>收藏常用文本和媒体，按类型、标题和标签快速查找。</p></div><div class="suite-actions"><button class="suite-btn" @click="downloadJson('canvas-assets.json', assets)">导出素材</button><button class="suite-btn" @click="fileInput?.click()">导入素材</button><button class="suite-btn primary" @click="openCreate">新增素材</button><input ref="fileInput" hidden type="file" accept="application/json" @change="importAssets"></div></div>
    <div class="suite-filters"><input v-model="query" class="suite-input suite-search" type="search" placeholder="搜索标题、内容、标签或来源"><div class="suite-segments"><button v-for="item in types" :key="item.value" :class="{active:type===item.value}" @click="type=item.value">{{ item.label }}</button></div></div>
    <p v-if="message" class="asset-message" :class="{ error: isError }">{{ message }}</p>
    <div v-if="filtered.length" class="suite-grid"><article v-for="asset in filtered" :key="asset.id" class="suite-card asset-card"><div v-if="asset.cover" class="asset-cover"><img v-if="asset.type==='image'" :src="asset.cover" :alt="asset.title"><video v-else-if="asset.type==='video'" :src="asset.cover" controls></video></div><span class="asset-type">{{ typeName(asset.type) }}</span><h2>{{ asset.title }}</h2><p class="asset-content">{{ asset.content || asset.note || '暂无内容' }}</p><div class="asset-tags"><span v-for="tag in asset.tags" :key="tag">{{ tag }}</span></div><div class="suite-card-actions"><button class="suite-btn" @click="edit(asset)">编辑</button><button class="suite-btn" @click="copy(asset)">复制</button><button class="suite-btn danger" @click="remove(asset.id)">删除</button></div></article></div>
    <div v-else class="suite-empty">没有找到素材</div>
    <div v-if="showForm" class="suite-modal-backdrop" @click.self="showForm=false"><div class="suite-modal"><h2>{{ draft.id ? '编辑素材' : '新增素材' }}</h2><div class="suite-form"><label>类型<select v-model="draft.type" class="suite-select"><option value="text">文本</option><option value="image">图片</option><option value="video">视频</option></select></label><label>标题<input v-model="draft.title" class="suite-input" placeholder="给素材起一个容易检索的名字"></label><label>封面或媒体 URL<input v-model="draft.cover" class="suite-input" placeholder="粘贴图片或视频 URL"></label><label>标签<input v-model="tagText" class="suite-input" placeholder="多个标签用逗号分隔"></label><label>来源<input v-model="draft.source" class="suite-input" placeholder="手动添加 / 画布 / 提示词库"></label><label>备注<textarea v-model="draft.note" class="suite-textarea" rows="2"></textarea></label><label>内容<textarea v-model="draft.content" class="suite-textarea" rows="5" placeholder="保存提示词、说明文案或参考描述"></textarea></label><div class="suite-form-actions"><button class="suite-btn" @click="showForm=false">取消</button><button class="suite-btn primary" :disabled="!draft.title.trim()" @click="save">保存</button></div></div></div></div>
  </section>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
import { canvasStorage, downloadJson, makeId, readJsonFile, type LibraryAsset, type LibraryAssetType } from './storage'
const assets=ref(canvasStorage.assets()), query=ref(''), type=ref<'all'|LibraryAssetType>('all'), showForm=ref(false), tagText=ref(''), message=ref(''), isError=ref(false), fileInput=ref<HTMLInputElement|null>(null)
const empty=():LibraryAsset=>({id:'',type:'text',title:'',content:'',cover:'',tags:[],source:'手动添加',note:'',createdAt:new Date().toISOString()}); const draft=ref(empty())
const types=[{value:'all' as const,label:'全部'},{value:'text' as const,label:'文本'},{value:'image' as const,label:'图片'},{value:'video' as const,label:'视频'}]
const filtered=computed(()=>{const q=query.value.trim().toLowerCase();return assets.value.filter(a=>(type.value==='all'||a.type===type.value)&&(!q||[a.title,a.content,a.source,a.note,...a.tags].join(' ').toLowerCase().includes(q)))})
function persist(){canvasStorage.saveAssets(assets.value)} function typeName(v:LibraryAssetType){return ({text:'文本',image:'图片',video:'视频'} as const)[v]}
function cloneAsset(a:LibraryAsset):LibraryAsset{return {...a,tags:[...a.tags]}}
function setMessage(text:string,error=false){message.value=text;isError.value=error}
function openCreate(){draft.value=empty();tagText.value='';setMessage('');showForm.value=true} function edit(a:LibraryAsset){draft.value=cloneAsset(a);tagText.value=a.tags.join(', ');setMessage('');showForm.value=true}
function save(){const value={...draft.value,id:draft.value.id||makeId('asset'),tags:tagText.value.split(/[,，]/).map(v=>v.trim()).filter(Boolean),createdAt:draft.value.createdAt||new Date().toISOString()};const i=assets.value.findIndex(a=>a.id===value.id);if(i>=0)assets.value[i]=value;else assets.value.unshift(value);persist();showForm.value=false;setMessage('素材已保存')}
async function copy(a:LibraryAsset){const text=a.content||a.cover||a.note||a.title;if(!text){setMessage('这个素材没有可复制的内容',true);return}try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text)}else{const textarea=document.createElement('textarea');textarea.value=text;textarea.style.position='fixed';textarea.style.left='-9999px';document.body.appendChild(textarea);textarea.focus();textarea.select();document.execCommand('copy');textarea.remove()}setMessage('素材内容已复制')}catch{setMessage('复制失败，请检查浏览器剪贴板权限',true)}} function remove(id:string){if(confirm('确定删除这个素材吗？')){assets.value=assets.value.filter(a=>a.id!==id);persist();setMessage('素材已删除')}}
async function importAssets(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;const value=await readJsonFile<LibraryAsset[]>(file);if(Array.isArray(value)){assets.value=value;persist()} (e.target as HTMLInputElement).value=''}
</script>
<style scoped>.asset-message{margin:12px 0;color:#16825d}.asset-message.error{color:#c2410c}.asset-card{display:flex;flex-direction:column;min-height:210px}.asset-cover{aspect-ratio:16/9;margin:-16px -16px 14px;overflow:hidden;border-radius:7px 7px 0 0;background:#eef0f2}.asset-cover img,.asset-cover video{width:100%;height:100%;object-fit:cover}.asset-type{font-size:12px;color:#777}.asset-content{display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.asset-tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:12px}.asset-tags span{background:#eef0f2;padding:3px 7px;border-radius:4px;font-size:12px}.suite-card-actions{margin-top:auto;padding-top:15px}</style>
